title: Your Site Title
description: Your site description
keywords: keyword1, keyword2, keyword3
author: Your Name
image: https://your-image-url.com/image.jpg
url: https://your-github-username.github.io
